### PR TITLE
copy over helper files from deprecated pyethereum repo

### PR DESCRIPTION
**Pull request by oberstet**
this PR remove the `ethereum==2.3.2` dependency by copying over exactly the bits needed from that deprecated repo .. the license is the same (MIT), its a limited amount of code, and it can greatly simply running apps on pypy as not the whole tree of ethereum deps kicks in. at least that was our itch to fork .. but of course I'd prefer to share it back;)

### CODE REVIEW

**Comment by rmeissner** [comment]
cool, thanks for the update, I will check why travis is failing and merge it.

Are the logger injection files required?

**Comment by oberstet** [comment]
I added `slogging.py` as this is used in the other stuff

```
(cpy374_1) oberstet@intel-nuci7:~/scm/crossbario/py-eth-sig-utils$ find py_eth_sig_utils -name "*.py" -exec grep -Hi "slogging" {} \;
py_eth_sig_utils/slogging.py:# copied over from https://github.com/ethereum/pyethereum/blob/v2.3.2/ethereum/slogging.py
py_eth_sig_utils/utils.py:    from ethereum import slogging
py_eth_sig_utils/utils.py:    slogging.DEBUG(msg, *args, **kwargs)
(cpy374_1) oberstet@intel-nuci7:~/scm/crossbario/py-eth-sig-utils$ find py_eth_sig_utils -name "*.py" -exec grep -H "DEBUG" {} \;
py_eth_sig_utils/slogging.py:def DEBUG(msg, *args, **kwargs):
py_eth_sig_utils/slogging.py:    logger = getLogger("DEBUG")
py_eth_sig_utils/slogging.py:    logger.setLevel(logging.DEBUG)
py_eth_sig_utils/utils.py:def DEBUG(msg, *args, **kwargs):
py_eth_sig_utils/utils.py:    slogging.DEBUG(msg, *args, **kwargs)
```

but only for 1 function

https://github.com/rmeissner/py-eth-sig-utils/blob/80a43e0c498f83e0bd59f3aa3808dfb913e9d0b2/py_eth_sig_utils/utils.py#L550

which doesn't seem to be used anywhere in the other stuff copied over.

consequently, I removed `slogging` and `utils.DEBUG` and updated the PR

**Comment by oberstet** [comment]
alright, I fixed the deps, tested in a completely fresh venv (cpy 3.7), and CI is green now.

> cpy 3.8 has an unrelated issue in cytoolz currently: https://gist.github.com/oberstet/808485626ca7d3ddfde2126e554d23e8

**Comment by oberstet** [comment]
cool, thanks for merging!

> we'll delete our fork and depend on upstream (this) again - https://github.com/crossbario/autobahn-python/issues/1260

**Pull request merged**
